#!/bin/bash
set -eu

rc=$(mktemp)
out=$(mktemp)
out2=$(mktemp)
echo "PS1='$ '" > $rc
script $out -fqc "env TERM=dumb bash --rcfile $rc"  < ./misc/session_example.stdin > /dev/null

sed -n '/^=BEGINMARK=/,//p' $out | tail -n +3 > $out2

# prettify
cat $out2 | sed 's/^\$ .$//g' | sed 's/^\$ #/#/g'
