#!/usr/bin/env python3

from subprocess import check_output
import os
from os import path
import jinja2
from pprint import pprint

DOCDIR = path.join(path.dirname(path.dirname(path.abspath(__file__))), 'docs')
BINDIR = path.join(path.dirname(DOCDIR), 'bin')

def render(tpl_path, **context):
    path, filename = os.path.split(tpl_path)
    return jinja2.Environment(
        loader=jinja2.FileSystemLoader(os.path.join(DOCDIR, 'templs'))
    ).get_template(filename).render(context)

out = check_output('plash-list')
out = out.decode()
progs = sorted((i.split(None, 1) for i in out.splitlines()))

with open(path.join(DOCDIR, 'index.html'), 'w') as f:
    f.write(render('index.html', progs=progs))

filedocs = []
for binfile in os.listdir(BINDIR):
    if binfile.startswith('.'):
        continue
    fname = path.join(BINDIR, binfile)
    with open(fname) as f:
        read = f.read()
    lines = read.splitlines()
    
    # get doc out of source code
    doc = []
    lines.pop(0)
    lines.pop(0)
    usage = lines.pop(0)[2:]
    while lines:
        line = lines.pop(0)
        if not line.startswith('#'):
            break
        doc.append(line[2:])
    filedocs.append({'code': read, 'doc': '\n'.join(doc), 'prog': binfile, 'usage': usage})


for item in filedocs:
    with open(path.join(DOCDIR, item['prog']+'.html'), 'w') as f:
        f.write(render('command.html', **item))
