#!/usr/bin/env python3

from subprocess import check_output
import os
import sys
from os import path
import jinja2

try:
    docs_out = sys.argv[1]
except IndexError:
    print('need arg', file=sys.stderr)
    sys.exit(1)

PROJECT_DIR = path.dirname(path.dirname(path.abspath(__file__)))
TEMPL_DIR = path.join(PROJECT_DIR, 'docs_templates')
BIN_DIR = path.join(PROJECT_DIR, 'plashlib/libexec')
TESTS_DIR = path.join(PROJECT_DIR, 'plashlib/tests')

def render(tpl_path, **context):
    path, filename = os.path.split(tpl_path)
    return jinja2.Environment(
        loader=jinja2.FileSystemLoader(TEMPL_DIR)).get_template(filename).render(context)

out = check_output(['plash', 'list'])
out = out.decode()
progs = sorted((i.split(None, 2)[1:] for i in out.splitlines()))

with open(path.join(docs_out, 'index.html'), 'w') as f:
    f.write(render('index.html', progs=progs))

filedocs = []
binfiles = [i for i in os.listdir(BIN_DIR) if not i.startswith('.')]
for binfile in binfiles:
    if binfile.startswith('.'):
        continue

    try:
        with open(path.join(TESTS_DIR, binfile)) as f:
            test_code = f.read()
    except FileNotFoundError:
        test_code = None

    fname = path.join(BIN_DIR, binfile)
    with open(fname) as f:
        read = f.read()
    lines = read.splitlines()

    # get doc out of source code
    doc = []
    lines.pop(0)
    lines.pop(0)
    while lines:
        line = lines.pop(0)
        if not line.startswith('#'):
            break
        doc.append(line[2:])
    subcommand = binfile.split('-', 1)[1]
    filedocs.append({'test_code': test_code, 'code': read, 'doc': '\n'.join(doc), 'prog': subcommand})

for item in filedocs:
    with open(path.join(docs_out, item['prog'] + '.html'), 'w') as f:
        f.write(render('command.html', **item))
