#!/bin/bash
set -eu

# usage: plash test [TEST-PREFIX]
# Run unit tests

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PS4='+ ${BASH_SOURCE}:${LINENO} '

#mkdir -p /var/lib/plash/tmp
export PATH=$DIR/../bin:$PATH
export PYTHONPATH=$DIR/..:${PYTHONPATH:-}
tmp=$(mktemp -d /var/tmp/plashtest-XXXXXXXX) # we can't use /tmp or /var/tmp (why?)
export PLASH_DATA=$tmp
plash-init

BUSYBOX=$(plash-import-tar $DIR/../misc/busybox.tar 2> /dev/null)
export BUSYBOX


log=$(mktemp)
program_exit=0
last_arg="${@: -1}"
testfiles=$(find ./tests/ -type f ! -iname "*.sw*" -iname "${1:-}*")
for script in $testfiles ; do
  printf ${script:8} # magic 8 is the length of "./tests/"
  "$script" > $log 2>&1 &
  if wait $!; then
    echo ' OK'
  else
    echo ' ERROR'
    program_exit=1
    test_mark_line=$(grep -n '^+ : ' $log | tail -n1 | cut -d: -f1)
    if [[ $test_mark_line =~ ^-?[0-9]+$ ]]; then
        tail -n +$test_mark_line $log | sed 's/^/  | /'  >&2 
    else
        cat $log | sed 's/^/  | /'  >&2 
    fi
    echo
  fi
done

exit $program_exit
