#!/bin/sh
set -ex

export PLASH_KILL_PARENT_ON_EXCEPTION=1

tmp=$(mktemp -d)

#
# plash add-layer
#

: adding a nonexistent layer
(! plash add-layer 0 /doesnotexists_asdf8)

: nonexistent container
(! plash add-layer 99999 $tmp)

: bad container
(! plash add-layer xxxx $tmp)

#
# plash build
#
# arguments from plash build are directly passed to getscript
# so there is not much to do on this one


#
# plash create
#
: use the special root container
(! plash create 0)

: use nonexistent container
(! plash create 99999)

: use bad container id
(! plash create xxx)

: create with bad command
(! plash create xxx)

: create with unknown command
(! plash create 1 unknown_command)

: build error
(! plash create 1 sh -c false)


#
# plash export-tar
#
# export-tar is actually currently just a proxy to the tar command,
# so there is not such much we can test now
: export to directory
tmpdir=$(mktemp -d)
(! plash export-tar 1 /tmp)


#
# plash getscript
#
# TODO: well, that one will need a little bit more work


#
# plash import-lxcimages
#
(! plash import-lxcimages doesnotexistsimagey)


#
# plash import-tar
#
: empty file
tmpfile=$(mktemp)
(! plash import-tar "$tmpfile")

: non existent file
(! plash import-tar /filedoesnotexists)

: directory
tmpdir=$(mktemp -d)
(! plash import-tar "$tmpdir")


#
# plash import-url
#
: bad formated url
(! plash import-url blah)

: bad protocoll
(! plash import-url myproto://blah)

: bad tar file
(! plash import-url http://google.com)

: nonumeric port
(! plash import-url http://localhost:d)

: socket error
(! plash import-url http://localhost:-1)

: empty file
tmpfile=$(mktemp)
(! plash import-url "file://$tmpfile")

: non existent file
(! plash import-url "file:///myfiledoesnotexists")

: directory
(! plash import-url "file:///tmp")


#
# plash map
#
: use the special root container
(! plash map mykey 0)

: use nonexistent container
(! plash map mykey 99999)

: use bad container id
(! plash map mykey xxx)


#
# plash mount
#
: use nonexistent container
(! plash mount 99999 "$tmp")

: use bad container id
(! plash mount xxx "$tmp")

: use non existent dir
(! plash mount 1 /doesnotexists)


#
# plash nodepath
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash nodepath 0)

: use nonexistent container
(! plash nodepath 99999)

: use bad container id
(! plash nodepath xxx)


#
# plash parent
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash parent 0)

: use nonexistent container
(! plash parent 99999)

: use bad container id
(! plash parent xxx)


#
# plash rm
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash rm 0)

: use nonexistent container
(! plash rm 99999)

: use bad container id
(! plash rm xxx)


#
# plash run
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash run 0)

: use nonexistent container
(! plash run 99999)

: use bad container id
(! plash run xxx)


#
# plash runopts
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash runopts 0)

: use nonexistent container
(! plash runopts 99999)

: use bad container id
(! plash runopts xxx)


#
# plash sudo
#
: nonexistent command
(! plash sudo doesnotexists)
: nonzero exit status
(! plash sudo exit)


#
# plash with-mount
#
: use the special root container
mountpoint=$(mktemp -d)
(! plash with-mount 0 ls)

: use nonexistent container
(! plash with-mount 99999 ls)

: use bad container id
(! plash with-mount xxx ls)

# non zero exit status for programm
(! plash with-mount 1 false)

# non existent command
(! plash with-mount 1 does-not-exist-asdf)
