#!/bin/bash
set -xeu

: plash with-mount does not crash
plash with-mount 1 printf hi

: list root dir
out=$(plash with-mount 1 ls | xargs)
[[ " $out " == *' home '* ]]
[[ " $out " == *' usr '* ]]
[[ " $out " == *' bin '* ]]

: check bad exit gets propagated
! plash with-mount 1 exit 7

: mount gets unmounted
before=$(cat /proc/mounts | grep "/index/1" | wc -l)
plash with-mount 1 true
! plash with-mount 1 false
after=$(cat /proc/mounts | grep "/index/1" | wc -l)
test $before = $after

# tar the container filesystem to /dev/null
plash with-mount 1 tar -cf - . > /dev/null
