#!/bin/bash
set -xeu

: create container 1, 2, and 3
plash build -i 1 --bust-cache
plash build -i 1 --bust-cache

: simple cache set and get
plash map mykey 1
test $(plash map mykey) == 1

: overwrite already set cache
plash map mykey2 1
plash map mykey2 2
test $(plash map mykey2) == 2

: attemptint to cache nonexistent container
! plash map thisismykey 9999999999

: remove key
plash map rkey 1
plash map rkey ''
out=$(plash map rkey)
test "$out" = ""
