#!/bin/sh
set -eux

export PLASH_KILL_PARENT_ON_EXCEPTION=1

: basic test
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--entrypoint
/bin/printf
--from
1
' >> $plashfile
chmod 700 $plashfile
test $("$plashfile" printf_that) = printf_that

: entrypoint not found
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--entrypoint
/usr/bin/notfoundxxxx
--from
1
' >> $plashfile
chmod 700 $plashfile
(! $plashfile)

: build error - bad build args
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--entrypoint
/bin/true
--asdf
' >> $plashfile
chmod 700 $plashfile
(! $plashfile)
