#!/bin/sh
set -xeu

export PLASH_KILL_PARENT_ON_EXCEPTION=1

: delete one container
newcont=$(plash build -f 1 --invalidate-layer)
plash nodepath $newcont
plash rm $newcont
(! plash nodepath $newcont)

: error with nonexistent container
(! plash rm 9999999)

: delte by build instruction
plash build -f 1 --run 'touch /plash-rm-test-file'
plash rm  -f 1 --run 'touch /plash-rm-test-file'
