#!/bin/bash
set -xeu

tmp=$(mktemp -d)
plash mount 1 $tmp
grep  $tmp' '  /proc/mounts >/dev/null || {
  echo 'Could not find mountpoint in /proc/mounts '
  exit 1
}
test -d $tmp/usr
test -d $tmp/bin
test -d $tmp/var
