#!/bin/sh
set -xeu

export PLASH_KILL_PARENT_ON_EXCEPTION=1

: delete one container
newcont=$(plash build -f 1 --invalidate-cache)
plash nodepath $newcont
plash rm $newcont
(! plash nodepath $newcont)

: error with nonexistent container
(! plash rm 9999999)

: delte by build instruction
plash build -f 1 --run 'touch /plash-rm-test-file'
plash rm  -f 1 --run 'touch /plash-rm-test-file'

: delete two containers
newcont1=$(plash build -f 1 --invalidate-cache)
newcont2=$(plash build -f 1 --invalidate-cache)
plash rm "$newcont1" "$newcont2"
(! plash nodepath $newcont1)
(! plash nodepath $newcont2)

: delete by two build instruction
plash build -f 1 --run 'touch /plash-rm-test-file1'
plash build -f 1 --run 'touch /plash-rm-test-file2'
plash rm -f 1 --run 'touch /plash-rm-test-file1' -- -f 1 --run 'touch /plash-rm-test-file2'
