#!/bin/sh
set -eux

: plash init populates dir
export PLASH_DATA=$(mktemp -d)
plash init
out=$(ls -A $PLASH_DATA)
test -n "$out"

: calling plash init two times does not crash
export PLASH_DATA=$(mktemp -d)
plash init
plash init

: plash init creates dir
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
plash init
out=$(ls -A $tmp/myplashdata)
test -n "$out"

! (PLASH_DATA=/tmp/bla:blub plash init) # bad char
! (PLASH_DATA=/tmp/bla:blu plash init) # bad chars

! (PLASH_DATA=/tmp/bla:blu plash init) # bad chars

