#!/bin/sh
set -eux

: check that plash init populates dir
export PLASH_DATA=$(mktemp -d)
plash init
out=$(ls -A $PLASH_DATA)
test -n "$out"

: calling plash init two times does not crash
export PLASH_DATA=$(mktemp -d)
plash init
plash init

: plash init creates dir
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
plash init
out=$(ls -A $tmp/myplashdata)
test -n "$out"

: union taste can be changed
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
PLASH_INIT_UNION_TASTE=xxx plash init
out=$(cat $tmp/myplashdata/config/union_taste)
test "$out" = xxx

: default union taste is unionfs-fuse
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
(
unset PLASH_INIT_UNION_TASTE
plash init
)
out=$(cat $tmp/myplashdata/config/union_taste)
test "$out" = unionfs-fuse
