#!/bin/bash
set -xeu

tmp=$(mktemp -d)
plash mount 1 $tmp
grep  $tmp' '  /proc/mounts >/dev/null || {
  echo 'Could not find mountpoint in /proc/mounts '
  exit 1
}
test -d $tmp/usr
test -d $tmp/bin
test -d $tmp/var

: check bad chars
tmp=$(mktemp -d)
changesdir=$tmp/'!@#$%^&*()'
mkdir $tmp/mp
mkdir $changesdir
(! plash mount 1 /tmp/mp "$changesdir" )
