#!/bin/sh
set -xeu

: create an empty file
plash run 1 touch /a

: run a program on the base layer of a container
plash build -f 1
out=$(plash run 1 echo hellow)
test "$out" = hellow

: run something with an layer
new=$(plash create 1 true)
out=$(plash run $new echo hi)
test "$out" = hi

: check the current dir is mapped
cd /tmp
out=$(plash run 1 pwd)
test "$out" = $(pwd)
cd -

: check that exit status get propagaded to the outside
set +e
plash run 1 sh -c 'exit 42'
test $? -eq 42 || exit 1
set -e

: check that environment variables are exported to the container
out=$(MYENV=123 plash run 1 sh -c 'echo $MYENV')
test $out = 123

: test a mount - actually a runopts test
tmp=$(mktemp)
changesdir=$(mktemp -d)
plash runopts -c $changesdir -b /etc/passwd 1 cat /etc/passwd > $tmp
cat $tmp
cmp /etc/passwd $tmp

: test auto build
plash run -f 1 --invalidate-layer -- ls

: mounts get cleanuped
new=$(plash create 1 ls)
before=$(cat /proc/mounts | grep "/index/$new" | wc -l)
plash run $new ls
after=$(cat /proc/mounts | grep "index/$new" | wc -l)
test $before = $after

: behavior when the command was not found
set +e
out=$(plash run 1 mycmdnotfound 2>&1)
exit=$?
set -e
set "$exit" = 127
test "$out" = "mycmdnotfound: command not found"

: test PATH from /etc/login.defs - simple
out=$(plash run -f 1 --write-file /etc/login.defs 'ENV_PATH /here' -- /bin/printenv PATH)
test "$out" = /here

: test PATH from /etc/login.defs - with PATH= prefix - see man login.defs for spec
out=$(plash run -f 1 --write-file /etc/login.defs 'ENV_PATH PATH=/here' -- /bin/printenv PATH)
test "$out" = /here

: test PATH from /etc/login.defs - funny whitespaces
out=$(plash run -f 1 --write-file /etc/login.defs '  ENV_PATH     PATH=/here   ' -- /bin/printenv PATH)
test "$out" = /here

: test PATH from /etc/login.defs - no ENV_PATH
out=$(plash run -f 1 --write-file /etc/login.defs '# mycomment' -- /bin/printenv PATH)
test "$out" = /bin:/usr/bin  # use default one

: test PATH from /etc/login.defs - space missing
out=$(plash run -f 1 --write-file /etc/login.defs 'ENV_PATH/here' -- /bin/printenv PATH)
test "$out" = /bin:/usr/bin  # use default one
