#!/bin/sh
set -exu

: simple call
out=$(ls "$PLASH_DATA"/tmp)
test "$out" = "" # assert empty tmp
plash run -f 1 -- true
out=$(ls "$PLASH_DATA"/tmp)
echo "$out" | grep plashtmp # assert output contains plashtmp
plash cleantmp
out=$(ls "$PLASH_DATA"/tmp)
test "$out" = "" # assert empty tmp
