#!/bin/sh

set -eu

username=$(id -un)
getuid=$(id -u)
groupname=$(id -gn)
getgid=$(id -g)

tmpdir=$(mktemp -d)
fifo="$tmpdir"/fifo
mkfifo "$fifo"


setupidns(){
  prog="$1"
  id="$2"
  name="$3"
  file="$4"

  if ! command -v "$prog" >/dev/null; then
    echo 'plash: command not found: '"$prog" \
    ' (package typically called `uidmap` or `shadow-utils`)' >&2
    exit 1
  fi

  found=0
  if [ -f "$file" ]; then
    while IFS=: read -r query start count
    do
    if [ "$query" = "$id" ] || [ "$query" = "$name" ]; then
        "$prog" "$pid" 0 "$getgid" 1 1 "$start" "$count"
        found=1
        break
    fi
    done <"$file"
  fi
  if [ "$found" = 0 ]; then
    echo "plash: please configure a subgid/uid range for the" \
    " user $name in /etc/subuid and /etc/subgid"
    exit 1
  fi
}

child(){
  read -r pid < "$fifo"
  setupidns newuidmap "$getuid" "$username" /etc/subuid
  setupidns newgidmap "$getgid" "$groupname" /etc/subgid
  echo ok > "$fifo"
}
child &

exec unshare --user --mount sh -euc '
echo $$ > '"$fifo"'
eval "read -r status < '"$fifo"'" 2> /dev/null
if [ $# = 0 ]; then
  default_shell=$(getent passwd '"$username"' | cut -d: -f 7)
  exec "$default_shell"
else
  exec "$@"
fi
' -- "$@"
