#!/bin/sh

set -eu

username=$(id -un)
getuid=$(id -u)
groupname=$(id -gn)
getgid=$(id -g)

tmpdir=$(mktemp -d)
fifo="$tmpdir"/fifo
mkfifo "$fifo"


setupidns(){
  while IFS=: read -r query start count
  do
  if [ "$query" = "$2" ] || [ "$query" = "$3" ]; then
      "$1" "$pid" 0 "$getgid" 1 1 "$start" "$count"
      break
  fi
  done <"$4"
}

child(){
  read -r pid < "$fifo"
  setupidns newuidmap "$getuid" "$username" /etc/subuid
  setupidns newgidmap "$getgid" "$groupname" /etc/subgid
  echo ok > "$fifo"
}

child &
( sleep 3 && echo timeout > "$fifo" ) &

exec unshare --user --mount sh -euc '
echo $$ > '"$fifo"'
read -r status < '"$fifo"'
if [ "$status" = "timeout" ]; then
 echo "child failed"
 exit 1
fi
exec "$@"
' -- "$@"
