#!/usr/bin/env python3
#
# usage: plash import-url URL
# Import a container from an url.

import sys
from os.path import join
from plash import utils
from subprocess import CalledProcessError, check_call

if len(sys.argv) < 2:
    utils.die_with_usage()

tmpdir = utils.plash_call("mkdtemp")
rootfs = join(tmpdir, "rootfs")
with utils.catch_and_die([CalledProcessError, KeyboardInterrupt]):
    check_call(
        [
            "curl",
            "--progress-bar",
            "--fail",
            "--location",
            "--output",
            rootfs,
            sys.argv[1],
        ]
    )
    check_call(["plash", "import-tar", rootfs])
