#!/usr/bin/env python3
#
# usage: plash import-tar [ TARFILE ]
# Create a container from a tar file.
# If the TARFILE argument is ommited, the tar file is read from stdin.

import sys
from subprocess import CalledProcessError, check_call

from plash import utils

try:
    tarfile = sys.argv[1]
except IndexError:
    tarfile = "-"

tmpdir = utils.plash_call("mkdtemp")
with utils.catch_and_die([CalledProcessError]):
    check_call(
        ["plash", "sudo", "tar", "--exclude=./dev/*", "-C", tmpdir, "-xf", tarfile]
    )

# we want /etc/resolv.conf to not be a symlink and to exist as a file.
# Otherwise mounting over it later does not work.  this should be solved in a
# more generic way in runopts
resolvconf = os.path.join(tmpdir, "etc/resolv.conf")
try:
    os.unlink(resolvconf)
except FileNotFoundError:
    pass
with open(resolvconf, "w") as f:
    f.seek(0)
    f.truncate()

utils.plash_exec("add-layer", "0", tmpdir)
