#!/bin/bash
#
# usage: plash import-lxc DISTRO:VERSION [--dry]
# Import image from linuxcontainers.org
# if --dry is set, the image url is printed but not imported

set -e
set -o pipefail

INDEX_URL=https://images.linuxcontainers.org/meta/1.0/index-user


if ! [[ "$1" = *':'* ]]; then
  echo "usage: plash import-lxc DISTRO:VERSION [--dry]" >&2
  exit 1
fi

match=$(curl --silent --fail --location $INDEX_URL |
  awk -F";" '$3 == "amd64" && $4 == "default" { print $1":"$2" "$6 }' |
  awk -v a="$1" 'a == $1 { print $2 }'
)

if [ -z "$match" ]; then
  echo "plash error: no match for \"$1\" (check $INDEX_URL)" >&2
  exit 1
fi

rootfs=https://images.linuxcontainers.org"$match"rootfs.tar.xz

if [[ "$2" = "--dry" ]]; then
  echo $rootfs
else
  exec plash import-url "$rootfs" "$rootfs".asc
fi
