#!/bin/bash
#
# usage: plash import-url URL [ GPG_SIGNATURE_URL ]
# Import a container from an url.

if [ -z "$1" ]; then
  echo "# usage: plash import-url URL [ GPG_SIGNATURE_URL ]" >&2
  exit 1
fi

set -e
set -o pipefail

# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

gpg_keyring="$script_dir"/../data/trusted_gpg_keyring
tmpdir=$(plash mkdtemp)
rootfs="$tmpdir/rootfs"
rootfs_sig="$tmpdir/rootfs.sig"

# downlaod given availabe ulr
curl --progress-bar --fail --location --output "$rootfs" "$1"

# maybe check the signature
if ! [ -z "$2" ] && hash gpgv 2> /dev/null; then
   curl --silent --location --fail "$2" --output "$rootfs_sig"
   gpgv --quiet --keyring "$gpg_keyring" - "$rootfs" < "$rootfs_sig"
fi

exec plash import-tar "$rootfs"
