#!/usr/bin/env python3
#
# usage: plash import-tar [ TARFILE ]
# Create a container from a tar file.
# If the TARFILE argument is ommited, the tar file is read from stdin.

import sys
from subprocess import CalledProcessError, check_call

from plash import utils

try:
    tarfile = sys.argv[1]
except IndexError:
    tarfile = "-"

tmpdir=utils.plash_call("mkdtemp")
with utils.catch_and_die([CalledProcessError]):
    check_call(["plash", "sudo", "tar", "-C", tmpdir, "-xf", tarfile])
utils.plash_exec("add-layer", "0", tmpdir)
