#!/bin/bash
set -e

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for f in $DIR/../bin/*
do
  first_line=$(head -n1 $f)
  if ! [[ "$first_line" == '#!/usr/bin/env python3' || "$first_line" == '#!/bin/sh' ]] ; then
    echo "Unsupported shebang in file $(realpath $f): $first_line"
  fi
done
