#!/bin/bash



: fetch alpine linux
plash -A -- true

: download the silver searchver and run it
plash build -A the_silver_searcher
plash b run -A the_silver_searcher -- ag --help

: install package with pip3
plash -A py3-pip -l --pip3 dotfiles -- dotfiles -h
