#!/bin/bash
set -xeu

: specifying - as a file
tmp=$(mktemp)
plash-export-tar 1 - > $tmp
tar --list -f $tmp >/dev/null

: only one argument
tmp=$(mktemp)
plash-export-tar 1 > $tmp
tar --list -f $tmp >/dev/null

: specifying a real file
tmp=$(mktemp)
plash-export-tar 1 $tmp
tar --list -f $tmp >/dev/null
