#!/bin/bash
set -xeu

tmp=$(mktemp -d)
plash-build --os busybox
plash-mount busybox $tmp
grep  $tmp' '  /proc/mounts >/dev/null || {
  echo 'Could not find mountpoint in /proc/mounts '
  exit 1
}
test -d $tmp/usr
test -d $tmp/bin
test -d $tmp/var
