set -xeu
# vim: set filetype=sh:
zesty=$(plash.build zesty --bust-cache)

echo 'TEST: run a program on the base layer of a container'
plash.build $zesty
out=$(plash.run $zesty -- echo hellow)
test "$out" == hellow

echo 'TEST: create a new layer and check that for programs' \
' the current working directory is mapped'
newcont=$(plash.build $zesty --bust-cache)
cd /tmp
out=$(plash.run $newcont pwd)
test "$out" == "/tmp"

echo 'TEST: check that exit status get propagaded to the outside'
(
set +e
plash run $zesty sh -c 'exit 42'
test $? -eq 42 || exit 1
)
