#!/bin/bash
set -e

log=$(mktemp)
program_exit=0
tmp=$(mktemp --directory --tmpdir=/var/lib/plash/tmp)
export PLASH_DATA=$tmp
plash.init
plash -o alpine3.6

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for script in $DIR/../tests/* ; do
  test $(basename $script) == $(basename ${BASH_SOURCE[0]}) && continue
  printf $(basename "$script")
  (
  PATH=$DIR/bin:$PATH
  export PS4='+ ${BASH_SOURCE}:${LINENO} '
  exec > $log 2>&1
  exec "$script"
  ) &
  if wait $!; then
    echo ' OK'
  else
    echo ' ERROR'
    program_exit=1
    tail -n3 <(cat -n $log) >&2
    echo
  fi
done

exit $program_exit
