#!/bin/bash
set -e

log=$(mktemp)
program_exit=0

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for script in $DIR/* ; do
  test $(basename $script) == $(basename ${BASH_SOURCE[0]}) && continue
  printf $(basename "$script")
  (
  PATH=$DIR/bin:$PATH
  export PS4='+ ${BASH_SOURCE}:${LINENO} '
  exec > $log 2>&1
  set -x
  source "$script"
  ) &
  if wait $!; then
    echo ' OK'
  else
    echo ' ERROR'
    program_exit=1
    tail -n3 <( cat -n $log ) >&2
    echo
  fi
done

exit $program_exit
