#!/bin/sh
set -ex

: it returns something it gets from stdin
out=$(echo 'myrun' | plash eval --run-stdin)
test $out = myrun

: feeding 4 lines returns 4 lines
lines=$(printf 'line1\n2\n3\n4' | plash eval --run-stdin | wc -l)
test "$lines" = 4
