#!/bin/bash

set -eux

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# skip if jinja2 is not installed
if ! $(python3 -c 'import jinja2'); then
  echo "SKIP MARKER"
  exit 1
fi

if ! $(command -v dot); then
  echo "SKIP MARKER"
  exit 1
fi

: simple gen-docs invocation
tmpd=$(mktemp -d)
"$DIR"/../../www/generate "$tmpd"

: test an index is created
stat "$tmpd"/index.html
