#!/bin/bash
set -xeu

fresh(){
    plash build -f 1 --invalidate-layer
}

: building container succeeds
fresh

: building container with multiple layers succeeds
plash build -f 1 -l --invalidate-layer -l --invalidate-layer -l --invalidate-layer -l --invalidate-layer

: changes in builded container persists
cont=$(fresh)
newcont=$(plash build -f $cont -x 'touch /hellow')
plash run $newcont stat /hellow

: recurring builds are cached
cont=$(fresh)
stderr=$(mktemp)
plash build -f $cont -x 'touch /a' 2> $stderr
test -s $stderr # its not empty
plash build -f $cont -x 'touch /a' 2> $stderr
(! test -s $stderr) # its empty

: any bad exit status when building returns exit code 1
cont=$(fresh)
set +e
plash build -f $cont -x 'exit 42'
test 1 -eq $? || exit 1
set -e

: nonexistent base container fails
(! plash build -f 999)

: only providing the container returns that container
out=$(plash build -f 1)
test "$out" = 1

: bad build option fails
(! plash build --my-bad-opiton)
