#!/bin/sh
set -exu
# build container 2 and 3
plash build -f 1 --invalidate-layer

: very simple call
plash clean

: check that $PLASH_DATA/index gets cleaned
out_before=$(ls "$PLASH_DATA"/index)
plash rm 2
plash clean
out_after=$(ls "$PLASH_DATA"/index)
test "$out_before" != "$out_after"

: check that $PLASH_DATA/map gets cleaned
cont=$(plash build -f 1 --invalidate-layer)
plash map key1 "$cont"
plash map key2 "$cont"
plash map key3 "$cont"
out=$(ls "$PLASH_DATA"/map)
echo "$out" | grep key1
echo "$out" | grep key2
echo "$out" | grep key3
plash rm 3  # delete the container the maps are referncing to
plash clean --clean-cache-keys
out=$(ls "$PLASH_DATA"/map/)
test "$out" = ""

: check that `plash clean` removes tmp directories
out=$(ls "$PLASH_DATA"/tmp)
test "$out" = "" # assert empty tmp
plash b run -f 1 -- true
out=$(ls "$PLASH_DATA"/tmp)
echo "$out" | grep plashtmp # assert output contains plashtmp
plash clean --clean-tmp
out=$(ls "$PLASH_DATA"/tmp)
test "$out" = "" # assert empty tmp

: check that some bad files does not lead to a crash
touch "$PLASH_DATA"/index/mybadfile
touch "$PLASH_DATA"/map/mybadfile
touch "$PLASH_DATA"/tmp/mybadfile
plash clean
