#!/bin/sh

set -eux

: argument is executed
test hi = "$(plash data printf "hi")"

: argument is executed in plash data
plash data ls | grep mnt
plash data ls | grep tmp
plash data ls | grep layer

: argument is executed in directory returned by invocation with no arguments
out1=$(plash data pwd)
out2=$(plash data)
test "$out1" = "$out2"

: HOME influences the plash data
test $(
unset PLASH_DATA
HOME=xx
plash data
) = "xx/.plashdata"

: PLASH_DATA is the plash data if set
test $(PLASH_DATA=xx plash data) = xx


: home directory in /etc/passwd is consulted as fallback
homedir=$(getent passwd "$(id -u)" | cut -d: -f6)
test "$(
unset HOME
unset PLASH_DATA
plash data
)" = "$homedir"/.plashdata
