#!/bin/bash
set -xeu

: tar written to file in first argument
tmp=$(mktemp)
plash export-tar 1 $tmp
tar --list -f $tmp >/dev/null

: tar printed to stdout if no arguments
tmp=$(mktemp)
plash export-tar 1 > $tmp
tar --list -f $tmp >/dev/null

: tar printed to stdout if `-` is the first argument
tmp=$(mktemp)
plash export-tar 1 - > $tmp
tar --list -f $tmp >/dev/null

: exported tar looks like a rootfs
tmp=$(mktemp)
plash export-tar 1 > $tmp
tar --list -f $tmp | grep /etc/passwd
tar --list -f $tmp | grep /bin/sh
