#!/bin/bash
set -xeu

# create a container 2
plash create 1 true

: setting key succeeds
plash map mykey 1

: accessing key returns setted key
test $(plash map mykey) == 1

: overwriting setted key succeeds
plash map mykey 2
test $(plash map mykey) == 2

: set cache for not existing container fails
(! plash map thisismykey 9999999999)

: remove cache key succeeds
plash map rkey 1
plash map rkey ''

: accessing removed cache key return empty string
out=$(plash map rkey)
test "$out" = ""

: accessing  cache key that never existed returns empty string
out=$(plash map mykeydoesnotestits)
test "$out" = ""

: removing removed key succeeds
plash map mkey 1
plash map mkey ''
plash map mkey ''

: setting key with a `/` fails
(! plash map hi/da 1)
