#!/bin/bash

set -eux

function has_tmpdir {
  tmproot="$(plash data realpath tmp)"
  [[ "$(ls $tmproot)" ]]
}  

function has_not_tmpdir {
  ! has_tmpdir
}  

: created tmpdir is in PLASH_DATA
tmpdir="$(plash mkdtemp)"
[[ "$tmpdir" = "$PLASH_DATA"* ]]

: created tmpdir is writable
tmpdir="$(plash mkdtemp)"
touch "$tmpdir/file"
mkdir "$tmpdir/dir"

: `plash clean` cleans tmpdir only if calling proccess died
has_not_tmpdir
sh -c "plash mkdtemp" # from a child process
has_tmpdir
plash clean
has_not_tmpdir
plash mkdtemp
has_tmpdir
plash clean
has_tmpdir

