#!/bin/bash

tmp=$(mktemp -d)
plash mount 1 $tmp
grep  $tmp' '  /proc/mounts >/dev/null || {
  echo 'Could not find mountpoint in /proc/mounts '
  exit 1
}
test -d $tmp/usr
test -d $tmp/bin
test -d $tmp/var

: check bad chars
tmp=$(mktemp -d)
changesdir=$tmp/'!@#$%^&*()'
mkdir $tmp/mp
mkdir $changesdir
(! plash mount 1 /tmp/mp "$changesdir" )

: no mount namespaces pollution 
tmpdir="$(mktemp -d)"
before=$(cat /proc/mounts | grep "/index/1" | wc -l)
plash mount 1 "$tmpdir"
after=$(cat /proc/mounts | grep "/index/1" | wc -l)
test $before = $after
