#!/bin/sh
set -eux

: check that purge delete everything in PLASH_DATA
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
echo 'yes' | plash purge
out=$(ls -A $PLASH_DATA)
test -n "$out"

: calling purge two times succeeds
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
plash purge --yes
plash purge --yes

: call purge on empty plash data succeed
export PLASH_DATA=$(mktemp -d)
plash purge --yes

: purge removes all data in PLASH_DATA
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
out=$(ls -A $PLASH_DATA)
test -n "$out"
plash purge --yes
out=$(ls -A $PLASH_DATA)
test -z "$out"

: not confirming does not delete the data
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
echo 'no' | plash purge
out=$(ls -A $PLASH_DATA)
test -n "$out"
