#!/bin/bash
set -eux

: user inside plash sudo is root
test $(plash sudo id -u) = 0

: no arguments gives shell
test "$(echo 'echo itsbash' | plash sudo)" = 'itsbash'

: unknown command
set +e
out=$(plash sudo cmdnotfound 2>&1)
set -e
[[ "$out" = *'No such file or directory'* ]]
[[ "$out" = *'cmdnotfound'* ]]

: different user and mount namespace
test ! "$(readlink /proc/self/ns/{mnt,user})" = "$(plash sudo readlink /proc/self/ns/{mnt,user})"

: same other mount namespaces
test "$(readlink /proc/self/ns/{cgroup,ipc,net,pid,uts})" = "$(plash sudo readlink /proc/self/ns/{cgroup,ipc,net,pid,uts})"
