#!/bin/bash
set -xeu

: arguments are executed 
test hi = "$(plash with-mount 1 printf hi)"

: current working directory looks like root file system
out=$(plash with-mount 1 ls | xargs)
[[ " $out " == *' home '* ]]
[[ " $out " == *' usr '* ]]
[[ " $out " == *' bin '* ]]

: bad command fails
(! plash with-mount 1 false) 

: able to tar current working directory
plash with-mount 1 tar -cf - . > /dev/null

: user friendly message when command not found
set +e
out=$(plash with-mount 1 cmdnotfound 2>&1)
set -e
[[ "$out" == *"cmdnotfound: command not found"* ]]

: omitted command leads to shell
test "$(echo "echo itshell" | plash with-mount 1)" = itshell
