#!/usr/bin/env python3

import sys
from plashlib.eval import get_macros, eval


try:
    import_macros = sys.argv[1]
except IndexError:
    import_macros = 'plashlib.macros.all'

eval([['import', import_macros]])

macros = get_macros()
prev_group = None
for name, func in sorted(
        macros.items(), key=lambda i: (i[1].__module__, i[0])):
    group = func.__module__
    if group != prev_group:
        prev_group is None or print()
        print('[{}]'.format(group))
    print('{: <16} = {}'.format(name, func.__doc__))
    prev_group = group
