#!/usr/bin/env python3
#
# usage: plash sudo [CMD1 [CMD2 ..]]
# Setup uid and gid mapped namespace,
# the execute command or start shell if not command supplied

import os
import sys
from plashlib.utils import get_default_shell, handle_help_flag, catch_and_die
from plashlib.unshare import unshare_if_user

handle_help_flag()
unshare_if_user()
cmd = sys.argv[1:]
if not cmd:
    cmd = [get_default_shell('/etc/passwd')]
with catch_and_die([FileNotFoundError], debug=cmd[0]):
    os.execlp(cmd[0], *cmd)
