#!/usr/bin/env python3
#
# usage: plash build <ACTIONS>
# Builds a container. Any command line options is interpreted as action,
# Use `--list` to list all available action.
#
# exit status:
# 1: Generic error code
# 2: Unrecognized arguments
# 3: Returning container from cache, not building
# 4: Build error - building returned non-zero exit status
#
#
# Examples:
#
# $ plash build -i ubuntu --run 'touch a'
# --> touch a
# --:
# 66
#
# $ plash build -i ubuntu --run 'touch a' --layer --run 'touch b'
# --> touch b
# --:
# 67
#
# $ plash build -i ubuntu --apt nmap
# --> apt-get update
# Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
# Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [235 kB]
# <snip>
# Setting up nmap (7.60-1ubuntu2) ...
# Processing triggers for libc-bin (2.26-0ubuntu2) ...
# --:
# 68

import re
import subprocess
import os
import sys
from plashlib.utils import hashstr, nodepath_or_die
from plashlib import ux
from subprocess import (DEVNULL, CalledProcessError, Popen, check_output, PIPE)

from plashlib.eval import LAYER_MARKER
from plashlib.stdlib import IMAGE_HINT_TEMPL
from plashlib.utils import catch_and_die, die, info, color, handle_help_flag, plash_map

handle_help_flag()
ux.assert_initialized()

with catch_and_die([CalledProcessError], silent=True):

    tokens = sys.argv[1:]
    inscript = ('\n'.join(tokens) + '\n').encode()
    script = subprocess.run(
        ['plash-getscript'],
        input=inscript,
        check=True,
        stdout=subprocess.PIPE).stdout.decode()

image_ir = re.compile(IMAGE_HINT_TEMPL.format('(.+)\n'))
matches = image_ir.findall(script)
script = image_ir.sub('', script)
if matches:
    image_hint = matches[-1]
else:
    die('no image specified', exit=2)

#
#  convert the image_hint into an container id, also use caching
#
if image_hint.isdigit():
    base_container = image_hint
    nodepath_or_die(base_container)
else:
    base_container = plash_map(image_hint.encode())
    if not base_container:
        with catch_and_die([CalledProcessError], silent=True):
            base_container = check_output(
                ['plash-import-lxcimages', image_hint]).decode().strip('\n')
        plash_map(image_hint.encode(), base_container)

# split the script in its layers
layers = script.split(LAYER_MARKER + '\n')
layers = [l for l in layers if l]

current_container = base_container
os.environ['PS4'] = color('--> ', 4)
for layer in layers:
    cache_key = hashstr(b':'.join([current_container.encode(),
                                   layer.encode()]))
    next_container = plash_map(cache_key.encode())
    if not next_container:

        # build and cache it
        p = Popen(
            ['plash-create', current_container, 'env', '-i', 'sh', '-l'],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            cwd='/')

        # for some reason in ubuntu the path is not exported
        # in a way this is a hack and should be fixed in ubuntu
        p.stdin.write(b'export PATH\n')

        p.stdin.write(b'set -ex\n')
        p.stdin.write(layer.encode())
        p.stdin.close()
        next_container = p.stdout.read().decode().strip('\n')
        exit = p.wait()
        if exit:
            # plash-create already prints a nice error message
            sys.exit(1)
        plash_map(cache_key.encode(), next_container)
        info('--:')
    current_container = next_container
build_container = current_container

print(current_container)
