#!/usr/bin/env python3
#
# usage: plash reset
# Prompts to delete all build data.

import os
import sys
from shutil import rmtree
from plashlib.utils import handle_help_flag, get_plash_data
from plashlib.unshare import unshare_if_user
from plashlib import ux

handle_help_flag()
plash_data = get_plash_data()
unshare_if_user()

if sys.argv[1:2] == ['--yes'] or input(
        'Delete all build data? [y/N] ') == 'y':

    #
    # don't delete the dir itself because it could be a mount
    #

    try:
        os.unlink(os.path.join(plash_data, 'id_counter'))
    except FileNotFoundError:
        pass

    try:
        os.unlink(os.path.join(plash_data, 'id'))
    except FileNotFoundError:
        pass

    try:
        os.unlink(os.path.join(plash_data, 'union_taste'))
    except FileNotFoundError:
        pass

    for dir in os.listdir(plash_data):
        rmtree(os.path.join(plash_data, dir))
