#!/bin/bash
# usage: plash test [TEST-PREFIX]
# Run unit tests

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

PS4='+ ${BASH_SOURCE}:${LINENO} '

#mkdir -p /var/lib/plash/tmp
export PATH=$DIR/libexec:$PATH
export PYTHONPATH=$DIR/..:${PYTHONPATH:-}
tmp=$(mktemp -d /tmp/plashtest-XXXXXXXX) # if we want to use it inside plash we cant user an overlay mounted fs
export PLASH_DATA=$tmp
plash init

plash import-tar $DIR/../testdata/busybox.tar > /dev/null

log=$(mktemp)
program_exit=0
last_arg="${@: -1}"
cd $DIR/../tests
testfiles=$(find . -type f ! -iname "*.sw*" -iname "${1:-}*")
for script in $testfiles ; do
  printf ${script:2} # magic 2 is the length of "./"
  "$script" > $log 2>&1 &
  if wait $!; then
    echo ' OK'
  else
    echo ' ERROR'
    program_exit=1
    test_mark_line=$(grep -n '^+ : ' $log | tail -n1 | cut -d: -f1)
    if [[ $test_mark_line =~ ^-?[0-9]+$ ]]; then
        tail -n +$test_mark_line $log | sed 's/^/  | /'  >&2 
    else
        cat $log | sed 's/^/  | /'  >&2 
    fi
    echo
  fi
done

exit $program_exit
