#!/usr/bin/env python3
#
# usage: plash rm [CONTAINER1 [CONTAINER2 [CONTAINER3 ...]]]
# Deletes the given containers.

import os
import sys
from shutil import rmtree
from tempfile import mkdtemp
from plashlib.utils import handle_build_args, handle_help_flag, nodepath_or_die, get_plash_data
from plashlib import ux

handle_help_flag()
handle_build_args()

for container in sys.argv[1:]:
    node = nodepath_or_die(container)
    tmp = mkdtemp(dir=get_plash_data())
    os.rename(node, tmp)
    rmtree(tmp)
