#!/usr/bin/env python3
#
# usage: plash nodepath CONTAINER
# Prints the path of a given container
# Example: `plash nodepath mycontainer | xargs tree`

import sys

from plashlib.utils import die_with_usage, handle_build_args, handle_help_flag, nodepath_or_die

handle_help_flag()
handle_build_args()

try:
    container = sys.argv[1]
except IndexError:
    die_with_usage()

nodepath = nodepath_or_die(container)
print(nodepath)
