#!/bin/bash

set -eu

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
tmpd=$(mktemp -d)
$SCRIPT_DIR/docs-generate "$tmpd"
cd "$tmpd"
echo -n 'plash.io' > CNAME # for github pages
git init
git add .
git commit -m 'deploy docs'
git push git@github.com:ihucos/plash-docs-deploy.git HEAD:master --force
