#!/bin/bash
set -eux

: Copying out a file system succeeds
tmpd=$(mktemp -d)
plash copy 1 "$tmpd"


: The copied out directory structure looks plausible
tmpd=$(mktemp -d)
plash copy 1 "$tmpd"
ls "$tmpd"/bin/sh
ls "$tmpd"/etc
