#!/bin/sh
set -eux

: basic test
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--entrypoint
/usr/bin/printf
' >> $plashfile
chmod 700 $plashfile
test $("$plashfile" printf_that) = printf_that

: entrypoint not found
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--entrypoint
/usr/bin/notfoundxxxx
' >> $plashfile
chmod 700 $plashfile
(! $plashfile)

: build error - bad build args
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--entrypoint
/bin/true
--asdf
' >> $plashfile
chmod 700 $plashfile
(! $plashfile)

: no --entrypoint
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1' >> $plashfile
chmod 700 $plashfile
(! $plashfile)

: test entrypoint-script macro
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--entrypoint-script
#!/bin/sh
echo hello
' >> $plashfile
chmod 700 $plashfile
test "$($plashfile)" = "hello"

: test cwd while building
cd /
plashfile=$(mktemp)
printf '#!/usr/bin/env plash-exec
--from
1
--run
pwd > /pwd
--entrypoint cat
' >> $plashfile
chmod 700 $plashfile
test "$($plashfile /pwd)" = "/tmp"
cd -
