#!/bin/bash
set -xeu

: all succeeds
plash help

: output includes some commands
plash help 2>&1| grep "plash run"
plash help 2>&1| grep "plash sudo"
plash help 2>&1| grep "plash with-mount"

: call for each available command succeeds
plash help 2>&1 | head -n -1 | cut -d' ' -f2 | xargs -L1 plash help
