#!/bin/sh
set -xeu

test_import_lxc () {
  plash import-lxc "$1" --dry | xargs curl --head --location --fail | grep "Content-Type: application/x-tar"
}
# test the test
(! test_import_lxc badimagname )

cont=$(plash import-lxc alpine:edge)
plash run $cont ls

: dry import of unknown image fails
(! plash import-lxc unknownos --dry)

: dry import returns https url
plash import-lxc alpine --dry | grep '^https://'

: Some images give a tar file
test_import_lxc alpine
test_import_lxc archlinux
test_import_lxc centos
test_import_lxc debian
test_import_lxc devuan
test_import_lxc fedora
test_import_lxc gentoo
test_import_lxc kali
test_import_lxc opensuse
test_import_lxc openwrt
test_import_lxc oracle
test_import_lxc sabayon
test_import_lxc ubuntu
test_import_lxc ubuntu-core

: dry import deprecated image succeeds
plash import-lxc trusty --dry

: dry import with version prefix succeeds
plash import-lxc ubuntu:cosmic --dry
plash import-lxc archlinux:current --dry
