#!/bin/sh
set -xeu

test_import_lxc () {
  plash import-lxc "$1" --dry | xargs curl --head --location --fail | grep "Content-Type: application/"
}
# test the test
(! test_import_lxc badimagname )

cont=$(plash import-lxc alpine:edge)
plash run $cont ls

: dry import of unknown image fails
(! plash import-lxc unknownos --dry)

: dry import returns https url
plash import-lxc alpine:edge --dry | grep '^https://'

: Some images give a tar file
test_import_lxc alpine:edge
test_import_lxc archlinux:current
test_import_lxc debian:sid
