#!/bin/sh
set -eux

: plash init populates population the PLASH_DATA
export PLASH_DATA=$(mktemp -d)
plash init
out=$(ls -A $PLASH_DATA)
test -n "$out"

: calling plash init two times does not crash
export PLASH_DATA=$(mktemp -d)
plash init
plash init

: plash init creates the directory in PLASH_DATA
tmp=$(mktemp -d)
export PLASH_DATA=$tmp/myplashdata
plash init
out=$(ls -A $PLASH_DATA)
test -n "$out"
