#!/bin/bash

set -eux

: `plash clean` cleans tmpdir only if calling proccess died
tmpd=$(plash mkdtemp)
plash clean
file $tmpd

: created tmpdir is in PLASH_DATA
tmpdir="$(plash mkdtemp)"
[[ "$tmpdir" = "$PLASH_DATA"* ]]

: created tmpdir is writable
tmpdir="$(plash mkdtemp)"
touch "$tmpdir/file"
mkdir "$tmpdir/dir"

