#!/bin/bash
set -exu

(! plash nodepath mynoexistentimage)

newcont=$(plash build --form id 1 --invalidate-layer)
nodepath=$(plash nodepath $newcont)
echo $nodepath | grep $newcont

layerup=$(plash build --form id $newcont --layer --invalidate-layer)
nodepath=$(plash nodepath $layerup)
echo $nodepath | grep $newcont
echo $nodepath | grep $layerup

: test positive number validation
[[ "$(plash nodepath xx   2>&1)" = *"positive number"* ]]
[[ "$(plash nodepath 222x 2>&1)" = *"positive number"* ]]
[[ "$(plash nodepath x222 2>&1)" = *"positive number"* ]]
[[ "$(plash nodepath -1   2>&1)" = *"positive number"* ]]
[[ "$(plash nodepath --   2>&1)" = *"positive number"* ]]
[[ "$(plash nodepath ""   2>&1)" = *"positive number"* ]]


: test querying for the special root image
[[ "$(plash nodepath 0 2>&1)" = *"special root image"* ]]
[[ "$(plash nodepath 0 --allow-root-container 2>&1)" = *"/layer/0" ]]
plash nodepath 0 --allow-root-container

: check bad PLASH_DATA error
[[ "$(PLASH_DATA=/xxx plash nodepath 1 2>&1)" = *"/xxx: No such file or directory" ]]

: no argument gets help message
[[ "$(plash nodepath 2>&1)" = *"usage: "* ]]
