#!/bin/sh
set -xeu

: plash nodepath subcommand does not know deleted containers
newcont=$(plash build -f 1 --invalidate-layer)
plash nodepath $newcont
plash rm $newcont
(! plash nodepath $newcont)

: Specifying an unknown container errors
(! plash rm 9999999)
