#!/bin/sh
set -xeu

: run a program and capture stdout
out=$(plash run 1 echo hellow)
test "$out" = hellow

: container is writeable
plash run 1 touch /a

: can be used with the `b` command
plash b run -f 1 --invalidate-layer -- ls

: no command arguments spawn a shell
test "$(echo 'echo iamshell' | plash run 1)" = iamshell
