#!/bin/bash
set -xeu

: Simple invocation succeeds
plash with-mount 1 printf hi

: Listing an images directories succeeds
out=$(plash with-mount 1 ls | xargs)
[[ " $out " == *' home '* ]]
[[ " $out " == *' usr '* ]]
[[ " $out " == *' bin '* ]]

: Bad exit status will get propagated
(! plash with-mount 1 sh -c 'exit 7')

: No mountspace polution
before=$(cat /proc/mounts | grep "/index/1" | wc -l)
plash with-mount 1 true
(! plash with-mount 1 false)
after=$(cat /proc/mounts | grep "/index/1" | wc -l)
test $before = $after

: You can tar out the image /dev/null
plash with-mount 1 tar -cf - . > /dev/null

: Comprehensive error message when an unknown command is given
set +e
out=$(plash with-mount 1 cmdnotfound 2>&1)
set -e
[[ "$out" == *"cmdnotfound: command not found"* ]]

: No command leads to shell
test "$(echo "echo itshell" | plash with-mount 1)" = itshell
