#!/bin/sh
set -ex
: just test the output of the apt package manager
out=$(plash eval --apt pkg1 'shell escape')
test "$out" = "apt-get update
apt-get install -y pkg1 'shell escape'"

: no argument has no output
out=$(plash eval --apt)
test "$out" = ""
