#!/bin/bash

set -eux

: simple invocation
test "$(plash b nodepath -f 1)" = "$(plash nodepath 1)"

: missing build arguments
[[ "$(plash b nodepath 1)" = *"no build arguments"*]]
[[ "$(plash b nodepath 1 2 3 4)" = *"no build arguments"*]]

: missing parameters
[[ "$(plash b nodepath)" = *"usage:"*]]

: build arguments order
plash b with-mount true -A
plash b with-mount -A -- true
