#!/bin/bash
set -xeu

# skip if in user mode because this takes
# too long on the fuse filesystem
test "$(id -u)" != 0 && {
  echo "SKIP MARKER"
  exit 1
}

plash build -f 1 --run 'touch /a'

: only one argument
tmp=$(mktemp)
plash export-tar 2 > $tmp

# XXX DEBUG CODE
printf "$tmp"
file $tmp
du -sh $tmp
head -c 200 $tmp

exit 1
tar --list -f $tmp >/dev/null

: specifying a real file
tmp=$(mktemp)
plash export-tar 2 $tmp
tar --list -f $tmp >/dev/null

: specifying '-' as a file
tmp=$(mktemp)
plash export-tar 2 - > $tmp
tar --list -f $tmp >/dev/null
