#!/bin/bash

set -eux

: no arguments result in bad exit status code
set +e
plash
test $? = 1
set -e

: help message when no arguments
[[ "$(plash 2>&1)" == *"plash is a container build"* ]]

: invoking with bad command
[[ "$(plash cmdnotfoundxxx 2>&1)" == *"no such command"* ]]

: test simple command call
test "$(plash run 1 printf hi)" = "hi"

: test implicit redirection to 'run'
test $(plash -f 1 -- printf hi) = "hi"

: test PLASH_NO_UNSHARE
(
export PLASH_NO_UNSHARE=1
test "$(plash sudo id)" = "$(id)"
)
