#!/bin/sh
set -eux

: check that purge works, confirm trough stdin
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
echo 'yes' | plash purge
out=$(ls -A $PLASH_DATA)
test -n "$out"

: purge two times
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
plash purge --yes
plash purge --yes

: call plash purge on empty plash data
export PLASH_DATA=$(mktemp -d)
plash purge --yes

: check that purge removes all data in the PLASH_DATA directory
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
out=$(ls -A $PLASH_DATA)
test -n "$out"
plash purge --yes
out=$(ls -A $PLASH_DATA)
test -z "$out"

: not confirming does not delete the data
export PLASH_DATA=$(mktemp -d)
plash init; plash data touch config/testmode
echo 'no' | plash purge
out=$(ls -A $PLASH_DATA)
test -n "$out"
