#!/bin/sh
set -xeu

: create an empty file - changedir is used for runopts
plash run 1 touch /a

: run a simple program
out=$(plash run 1 echo hellow)
test "$out" = hellow

: test auto build
plash b run -f 1 --invalidate-layer -- ls

: test that no arguments mean a shell is started
test "$(echo 'echo iamshell' | plash run 1)" = iamshell

: test variables can be specified as arguments

: use many big arguments
plash run 1 printf foooobarbasbasbbazzz foooobarbasbasbbazzz foooobarbasbasbbazzz foooobarbasbasbbazzz foooobarbasbasbbazzz foooobarbasbasbbazzz foooobarbasbasbbazzz 
