#!/bin/sh
set -xeu

: create an empty file - changedir is used for runopts
plash run 1 touch /a

: run a simple program
out=$(plash run 1 echo hellow)
test "$out" = hellow

: test auto build
plash run -f 1 --invalidate-layer -- ls
