#!/usr/bin/python3
import argparse
import atexit
import os
import subprocess
import sys
import tempfile
import uuid

args = sys.argv[1:]
cmd = []
filtered_args = []
found_first_opt = False
while args:
    arg = args.pop(0)
    if not arg.startswith('-') and not found_first_opt:
        cmd.append(arg)
    elif arg == '--':
        cmd += args
        args = None
    else:
        filtered_args.append(arg)
        found_first_opt = True

if not cmd:
    print("needs at least one command")
    sys.exit(0)

exportscript = os.path.join(os.path.dirname(sys.argv[0]), 'export')

tempfname = os.path.join(tempfile.gettempdir(), "plash-" + str(uuid.uuid4()))
p = subprocess.Popen([exportscript, cmd[0], tempfname] + filtered_args)
atexit.register(p.kill)
exit = p.wait()
if exit:
    sys.exit(exit)

p = subprocess.Popen([tempfname] + cmd[1:])
exit = p.wait()
print("*** plash: exit status {}".format(exit))
os.unlink(tempfname + '.squashfs')
os.unlink(tempfname)
