#!/bin/sh
: test the x shortuct
out=$(plash eval -x hi)
test "$out" = hi

: test pinned down version in shortcuts
plash import-lxc alpine:edge --dry
plash import-lxc ubuntu:focal --dry
plash import-lxc fedora:35 --dry
plash import-lxc debian:bullseye --dry
plash import-lxc centos:8 --dry
plash import-lxc archlinux:current --dry
