#!/bin/bash
# vim: set filetype=yaml:
./plash --ubuntu --include <(cat <<'YamlConfigDelimiter'
# ========== [YOUR CONFIG] ==============

- rebuild-when-changed: requirements.txt

- mount: .
# - pwd: .
- import-env: PWD
- eval:
  - cd $PWD

- layer

- eval: pip install -r ./requirements.txt


- layer
# - cmd: ls -a


# ======================================
YamlConfigDelimiter
)
