#!/bin/sh

plash \
  --os zesty \
  --apt python3 wget squashfs-tools python3-setuptools tree \
  --layer \
  --run \ 
  'rm -rf /var/cache/apt' \
  'rm -rf /var/lib/apt/lists' \
  'apt-get purge -y vim vim.tiny vim-common vim-runtime' \


--os
zesty

--apt
python3
wget
squashfs-tools
python3-setuptools
tree

--layer

--run 
rm -rf /var/cache/apt
rm -rf /var/lib/apt/lists
apt-get purge -y vim vim.tiny vim-common vim-runtime
