#!/bin/bash
set -e

log=$(mktemp)
program_exit=0

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
for config in $DIR/../test.d/*.sh ; do
  printf $(basename "$config")
  (
  export PS4='+ ${BASH_SOURCE}:${LINENO} '
  [ "$1" == chatty ] || exec > $log 2>&1
  set -x
  source "$config"
  ) &
  if wait $!; then
    echo ' OK'
  else
    echo ' ERROR'
    program_exit=1
    tail $log
    echo
  fi

done

exit $program_exit
