#!/usr/bin/env python3
#
# usage: plash run CONTAINER [ CMD1 [ CMD2 ... ] ]
# Run a container. Default command is the shell
# started.

import os
import shlex
import sys
from subprocess import check_call

from plash import utils

utils.handle_help_flag()
utils.handle_build_args()

try:
    container_id, *cmd = sys.argv[1:]
except ValueError:
    utils.die_with_usage()

changesdir = utils.mkdtemp()

os.execlp('plash-runopts', 'plash-runopts',
'-c', changesdir,
'-b', '/tmp',
'-b', '/home',
'-b', '/root',
'-b', '/etc/resolv.conf',
'-b', '/sys',
'-b', '/dev',
'-b', '/proc',
'--', container_id, *cmd)
