#!/usr/bin/env python3
#
# usage: plash import-url-as URL
# Import a url as a container

import sys
from os import execlp
from urllib.request import urlretrieve
from urllib.error import URLError
from http.client import HTTPException
from plash.utils import handle_help_flag, die_with_usage, catch_and_die, assert_initialized
from tempfile import mkstemp

handle_help_flag()
assert_initialized()

try:
    url = sys.argv[1]
except IndexError:
    die_with_usage()

tmpfile = mkstemp()[1]


def reporthook(count, block_size, total_size):
    if total_size:
        sys.stderr.write('Fetching... {}%\r'.format(
            round(100 * count * block_size / total_size)))


with catch_and_die(
    [HTTPException, ValueError, URLError],
        debug='geturl({})'.format(repr(url))):
    urlretrieve(url, tmpfile, reporthook=reporthook)

execlp('plash-import-tar', 'plash-import-tar', tmpfile)
