#!/usr/bin/env python3
#
# usage: plash with-mount CONTAINER [ CMD1 [ CMD2  ... ] ]
# Run something inside a mounted container.
# Example: plash with-mount -f alpine mv . /tmp/rootfs

import os
import sys
from subprocess import CalledProcessError, check_call

from plash.utils import (assert_initialized, catch_and_die, die, mkdtemp,
                         die_with_usage, handle_build_args, handle_help_flag, get_default_shell)

from plash.unshare import unshare_if_root, unshare_if_user
handle_help_flag()
handle_build_args()
assert_initialized()

try:
    container = sys.argv[1]
    cmd = sys.argv[2:]
except IndexError:
    die_with_usage()
default_shell = get_default_shell('/etc/passwd')
if not cmd:
    cmd = [default_shell]

mountpoint = mkdtemp()

unshare_if_root()
with catch_and_die([CalledProcessError], silent=True):
    check_call(['plash-mount', container, mountpoint])
unshare_if_user(extra_setup_cmd=['fusermount', '-u', mountpoint])
os.chdir(mountpoint)
try:
    os.execlp(cmd[0], *cmd)
except FileNotFoundError:
    sys.stderr.write('{}: command not found'.format(cmd[0]))
    sys.exit(127)
