#!/usr/bin/env python3

import subprocess
import os, sys
from plash import utils
from plash.unshare import unshare_if_user, unshare_if_root

#unshare_if_user()
#nshare_if_root()

lower1 = utils.mkdtemp()
lower2 = utils.mkdtemp()

# XXX SECURITY ESCAPE lower1 lower2
p = subprocess.Popen([
    'mount', '-t', 'overlay', 'overlay', '-olowerdir={}:{}'.format(
        lower1, lower2),
    os.path.join(utils.get_plash_data(), 'mnt')],
    stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)

exit = p.wait()
if exit:
    print('plash: test overlay invocation failed', file=sys.stderr)
else:
    print('plash: test overlay invocation succeeded', file=sys.stderr)
