#!/usr/bin/env python3
#
# usage: plash import-url-as URL
# Import a url as a container

import sys
from http.client import HTTPException
from os import execlp
from tempfile import mkstemp
from urllib.error import URLError
from urllib.request import urlretrieve

from plash.utils import (assert_initialized, catch_and_die, die_with_usage,
                         handle_help_flag)

handle_help_flag()
assert_initialized()

try:
    url = sys.argv[1]
except IndexError:
    die_with_usage()

tmpfile = mkstemp()[1]


def reporthook(count, block_size, total_size):
    if total_size:
        sys.stderr.write('plash: import-url: fetching... {}%\r'.format(
            round(100 * count * block_size / total_size)))


with catch_and_die(
    [HTTPException, ValueError, URLError],
        debug='geturl({})'.format(repr(url))):
    urlretrieve(url, tmpfile, reporthook=reporthook)

execlp('plash-import-tar', 'plash-import-tar', tmpfile)
