#!/usr/bin/env python3
#
# usage: plash with-mount CONTAINER EVAL1 [EVAL2 [EVAL3 ...]]
# Execute a command inside the container filesystem
# Example: plash with-mount alpine mv . /tmp/rootfs

import os
import sys
from subprocess import CalledProcessError, check_call
from tempfile import mkdtemp

from plash.utils import (assert_initialized, catch_and_die, die,
                         die_with_usage, handle_build_args, handle_help_flag)

from plash.unshare import unshare_if_root, unshare_if_user
handle_help_flag()
handle_build_args()
assert_initialized()

try:
    container = sys.argv[1]
    cmd = sys.argv[2:]
except IndexError:
    die_with_usage()

mountpoint = mkdtemp()

unshare_if_root()
with catch_and_die([CalledProcessError], silent=True):
    check_call(['plash-mount', container, mountpoint])
unshare_if_user(extra_setup_cmd=['fusermount', '-u', mountpoint])
os.chdir(mountpoint)
try:
    os.execlp(cmd[0], *cmd)
except FileNotFoundError:
    sys.stderr.write('{}: command not found'.format(cmd[0]))
