#!/usr/bin/env python3
#
# usage: plash list
# Lists all available plash commands

from os.path import dirname, join
from os import listdir
import sys
from plash.utils import handle_help_flag

handle_help_flag()

bin = dirname(sys.argv[0])
progs = [i for i in listdir(bin) if not i.startswith('.')]
max_prog_lenght = max(len(prog) for prog in progs)
for prog in sorted(progs):
    first_sentence = '<empty>'
    with open(join(bin, prog)) as f:
        lines = f.readlines()
    for line, next_line, next_next_line in zip(lines, lines[1:], lines[2:]):
        if line.startswith('# usage:'):
            first_sentence = next_line[2:-1].split('.')[0]
            if not first_sentence:  # try the next line
                first_sentence = next_next_line[2:-1].split('.')[0]

    assert first_sentence
    subcommand = prog[len('plash '):]
    print(('plash ' + subcommand).ljust(max_prog_lenght), first_sentence)
