#!/usr/bin/env python3
#
# usage: plash rm CONTAINER
# Deletes the given containers.
# There are no guarantess of any behavour for running containers

import os
import sys
from shutil import rmtree

from plash.utils import (get_plash_data, handle_build_args, handle_help_flag,
                         nodepath_or_die, die_with_usage, mkdtemp)

handle_help_flag()
handle_build_args()

try:
    container = sys.argv[1]
except IndexError:
    die_with_usage()

node = nodepath_or_die(container)
tmp = mkdtemp()
os.rename(node, tmp)
rmtree(tmp)
