#!/usr/bin/env python3
#
# usage: plash run CONTAINER [CMD1 [CMD2 ..]]
# Run a command inside a container. If no command is specified a shell is
# started.  The workdir and upperdir parameters can be used to save file system
# changes made inside the container.

import os
import sys
import shlex
from plash.utils import nodepath_or_die, handle_help_flag, die_with_usage, handle_build_args, get_plash_data
from subprocess import check_call
from tempfile import mkdtemp

handle_help_flag()
handle_build_args()

try:
    container_id, *cmd = sys.argv[1:]
except ValueError:
    die_with_usage()

os.execlp('plash-runopts', 'plash-runopts', '--', container_id, *cmd)
