#!/usr/bin/env python3
#
# usage: plash map KEY [ CONTAINER ]
# Get or set a container by a key. Use an empty container to delete a key.
#
# Example:
# $ plash build -f alpine
# 342
#
# $ plash map myfavorite 342
#
# $ plash map myfavorite
# 342
#
# $ plash build --from-map myfavorite
#342

import os
import sys
from os.path import join
from tempfile import mkdtemp

from plash.utils import (assert_initialized, catch_and_die, die_with_usage,
                         get_plash_data, handle_help_flag, nodepath_or_die)

handle_help_flag()
assert_initialized()

plash_data = get_plash_data()

try:
    key = sys.argv[1]
except IndexError:
    die_with_usage()

try:
    value = sys.argv[2]
except IndexError:
    value = None


def escape_cache_key(unescaped_cache_key):
    return unescaped_cache_key.replace('/', '%')


def cache_set(unescaped_cache_key, container_id):
    cache_key = escape_cache_key(unescaped_cache_key)
    nodepath = nodepath_or_die(container_id)
    with catch_and_die([OSError], debug='mkdtemp'):
        tmpdir = mkdtemp(dir=join(plash_data, 'tmp'))
        os.symlink(nodepath, join(tmpdir, 'link'))

        # rename will overwrite atomically the cache key if it already exists,
        # just symlink would not
        os.rename(
            join(tmpdir, 'link'), join(plash_data, 'cache_keys', cache_key))


def cache_rm(unescaped_cache_key):
    cache_key = escape_cache_key(unescaped_cache_key)
    with catch_and_die([OSError], debug='unlink'):
        try:
            os.unlink(join(plash_data, 'cache_keys', cache_key))
            return True
        except FileNotFoundError:
            return False


def cache_get(unescaped_cache_key):
    cache_key = escape_cache_key(unescaped_cache_key)
    try:
        nodepath = os.readlink(join(plash_data, 'cache_keys', cache_key))
    except FileNotFoundError:
        return
    if os.path.exists(nodepath):
        return os.path.basename(nodepath)


if value == '':
    cache_rm(key)
elif value is None:
    cont = cache_get(key)
    if cont:
        print(cont)
else:
    cache_set(key, value)
