#!/usr/bin/env python3

import os
import sys
from plash import utils

plash_data = utils.get_plash_data()
shell = utils.get_default_shell('/etc/passwd')
if not sys.argv[1:]:
    print(plash_data)
else:
    os.chdir(plash_data)
    os.execlp(sys.argv[1], sys.argv[1], *sys.argv[2:])
