#!/usr/bin/env python3

import subprocess
import os, sys
import ctypes
import errno
from plash import utils
from plash.unshare import unshare_if_user, unshare_if_root

utils.assert_initialized()
unshare_if_user()
unshare_if_root()

lower1 = utils.mkdtemp()
lower2 = utils.mkdtemp()

# value ignored since kernel 2.4
MS_MGC_VAL = 0xC0ED0000

libc = ctypes.CDLL('libc.so.6', use_errno=True)
# XXX SECURITY ESCAPE lower1 lower2
ret = libc.mount(b"overlay", b"/var/lib/plash/mnt", b"overlay", MS_MGC_VAL,
        "lowerdir={}:{}".format(lower1, lower2).encode())

if not ret:
    print('plash: test overlay worked', file=sys.stderr)
else:
    myerrno = ctypes.get_errno()
    errno_str = errno.errorcode.get(myerrno, myerrno)
    print('plash: test overlay failed ({})'.format(errno_str), file=sys.stderr)
    sys.exit(myerrno)





#p = subprocess.Popen([
#    'mount', '-t', 'overlay', 'overlay', '-olowerdir={}:{}'.format(
#        lower1, lower2),
#    os.path.join(utils.get_plash_data(), 'mnt')],
#    )
#
#exit = p.wait()
#print(exit)
#if exit:
#    print('plash: test overlay invocation failed', file=sys.stderr)
#else:
#    print('plash: test overlay invocation succeeded', file=sys.stderr)
