#!/usr/bin/env python3
#
# usage: plash sudo [CMD1 [CMD2 ..]]
# Setup uid and gid mapped namespace,
# the execute command or start shell if not command supplied

import os
import sys

from plash.unshare import unshare_if_user
from plash.utils import catch_and_die, get_default_shell, handle_help_flag

handle_help_flag()
unshare_if_user()
cmd = sys.argv[1:]
if not cmd:
    cmd = [get_default_shell('/etc/passwd')]

try:
    os.execlp(cmd[0], *cmd)
except FileNotFoundError:
    sys.stderr.write('{}: command not found\n'.format(cmd[0]))
    sys.exit(127)
