#!/usr/bin/env python3
#
# usage: plash run CONTAINER [ CMD1 [ CMD2 ... ] ]
# Run a container.
# If no command is specified, the containers default root shell is execed.
# The following host file systems are mapped to the container:
# - /tmp
# - /home
# - /root
# - /etc/resolv.conf
# - /sys
# - /dev
# - /proc

import os
import shlex
import sys
from subprocess import check_call

from plash import utils

utils.handle_help_flag()
utils.handle_build_args()

try:
    container_id, *cmd = sys.argv[1:]
except ValueError:
    utils.die_with_usage()

changesdir = utils.mkdtemp()

os.execlp('plash-runopts', 'plash-runopts',
'-c', container_id,
'-d', changesdir,
'-m', '/tmp',
'-m', '/home',
'-m', '/root',
'-m', '/etc/resolv.conf',
'-m', '/sys',
'-m', '/dev',
'-m', '/proc',
'--', *cmd)
