#!/bin/sh
set -eux

: user inside plash sudo is root
test $(plash sudo id -u) = 0

: no arguments gives shell
test "$(echo 'echo itsbash' | plash sudo)" = 'itsbash'

: unknown command
set +e
out=$(plash sudo cmdnotfound 2>&1)
set -e
test "$out" = 'cmdnotfound: command not found'
