#!/bin/sh
set -xeu

: create an empty file
plash run 1 touch /a

: run a program on the base layer of a container
plash build -f 1
out=$(plash run 1 echo hellow)
test "$out" = hellow

: run something with an layer
new=$(plash create 1 true)
out=$(plash run $new echo hi)
test "$out" = hi

: check the current dir is mapped
cd /tmp
out=$(plash run 1 pwd)
test "$out" = $(pwd)
cd -

: check that exit status get propagaded to the outside
set +e
plash run 1 sh -c 'exit 42'
test $? -eq 42 || exit 1
set -e

: check that environment variables are NOT exported to the container
out=$(MYENV=123 plash run 1 sh -c 'echo $MYENV')
test "$out" = ""

: check export via PLASH_EXPORT
out=$(PLASH_EXPORT=MYENV MYENV=123 V=a plash run 1 sh -c 'echo $MYENV$V')
test $out = "123"

: check export via PLASH_EXPORT - multiple vars
out=$(PLASH_EXPORT='MYENV:V' V=a MYENV=123 plash run 1 sh -c 'echo $MYENV$V')
test $out = "123a"

: test a mount - actually a runopts test
tmp=$(mktemp)
changesdir=$(mktemp -d)
plash runopts -c 1 -d $changesdir -m /etc/passwd cat /etc/passwd > $tmp
cat $tmp
cmp /etc/passwd $tmp

: test auto build
plash run -f 1 --invalidate-layer -- ls

: mounts get cleanuped
new=$(plash create 1 ls)
before=$(cat /proc/mounts | grep "/index/$new" | wc -l)
plash run $new ls
after=$(cat /proc/mounts | grep "index/$new" | wc -l)
test $before = $after

: behavior when the command was not found
set +e
out=$(plash run 1 mycmdnotfound 2>&1)
exit=$?
set -e
test "$exit" = 127

: test variable setting
out=$(plash run 1 MYV=101 printenv MYV)
test "$out" = 101
