#!/bin/sh
set -eux

: create container with a new file
new=$(plash create 1 touch /myfileah)
plash with-mount $new ls ./myfileah

: create a container via default shell that is with no args
echo 'echo hi' | plash create 1

# plash create tschuuh tschuuh train
plash create $(plash create $(plash create 1 true) true) true
