#!/usr/bin/env python3
# usage: plash copy CONTAINER DIR
#
# Copy the container's root filesystem to directory.

from os.path import abspath
import os
import sys

from plash import utils

utils.assert_initialized()
utils.handle_build_args()
utils.unshare_user()

try:
    container, outdir = sys.argv[1:3]
except ValueError:
    utils.die_with_usage()

tmpout = utils.mkdtemp()

utils.plash_call("with-mount", "--", container, "cp", "-r", ".", tmpout)

with utils.catch_and_die([OSError]):
    os.rename(tmpout, outdir)
