#!/usr/bin/env python3
#
# usage: plash help
# List all available subcommands.

import sys
import os
from os import listdir
from os.path import dirname, join, islink
import re

from plash.utils import handle_help_flag

FIRST_SENTENCE_RE = "# usage: .*?\n(?:#\n)*?# (.*?)\.".replace("#", "(?:#|//)")

handle_help_flag()

bin = dirname(sys.argv[0])
progs = [i for i in listdir(bin) if os.access(join(bin, i), os.X_OK)]
max_prog_lenght = len('plash ') + max(len(prog) for prog in progs)
for prog in sorted(progs):
    prog_path = join(bin, prog)

    if os.access(prog_path + ".c", os.F_OK):
        prog_path += ".c"

    if islink(prog_path):
        #continue # it's an alias
        links_to = os.readlink(prog_path)
        first_sentence = 'Alias for `plash {}`'.format(links_to)
    else:
        with open(prog_path) as f:
            content = f.read()
        found = re.findall(FIRST_SENTENCE_RE, content)
        if not found:
            first_sentence = '<empty>'
        else:
            first_sentence = found[0]
          

    assert first_sentence
    print(('plash ' + prog).ljust(max_prog_lenght), first_sentence)
print(('plash ' + '-*').ljust(max_prog_lenght), 'Fallback to `plash run`')
