#!/usr/bin/env python3
#
# usage: plash run CONTAINER [ CMD1 [ CMD2 ... ] ]
#
# Run a container. If no command is specified, the containers default root
# shell is executed.
#
# The following host file systems are mapped to the container:
# - /tmp
# - /home
# - /root
# - /etc/resolv.conf
# - /sys
# - /dev
# - /proc
#
# If you want more control about how the container is run, use `plash runopts`
#
# Parameters may be interpreted as build instruction.

import os
import sys

from plash import utils

utils.handle_build_args()

try:
    container_id, *cmd = sys.argv[1:]
except ValueError:
    utils.die_with_usage()


# use with login shell
cmd = ['sh', '-lc', 'exec env "$@"', '--'] + cmd

changesdir = utils.mkdtemp()

utils.plash_exec(
    'runopts',
    *((
        '-c',
        container_id,
        '-d',
        changesdir,
        '-m',
        '/tmp',
        '-r',
        '/home',
        '-m',
        '/root',
        '-m',
        '/etc/resolv.conf',
        '-m',
        '/sys',
        '-m',
        '/dev',
        '-m',
        '/proc',
        '--') + tuple(cmd)))
