#!/bin/bash
# usage: plash test [TEST-PREFIX]
# Run unit tests.
# You can filter tests to run by a prefix passed as first argument

set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_DIR="$DIR/../.."

log=$(mktemp)
program_exit=0
cd $PROJECT_DIR/tests
testfiles=$(find . -type f -executable -ipath "./${1:-}*" | sort)
for script in $testfiles ; do

  # setup test env
  tmp=$(plash mkdtemp) # if we want to use it inside plash we cant user an overlay mounted fs
  export PLASH_DATA=$tmp
  plash init
  plash data touch config/testmode
  plash import-tar $PROJECT_DIR/data/busybox.tar > /dev/null

  printf "% -20s" ${script:2} # magic 2 is the length of "./"
  env "$script" > $log 2>&1 &
  if wait $!; then
    echo ' PASS'
  else
    skip_marker=$(tail -n2 $log | head -n1)
    if test "$skip_marker" = 'SKIP MARKER'; then
      echo ' SKIP'
      continue
    fi
    echo ' FAIL'
    program_exit=1
    test_mark_line=$(grep -n '^+ : ' $log | tail -n1 | cut -d: -f1)
    if [[ $test_mark_line =~ ^-?[0-9]+$ ]]; then
        tail -n +$test_mark_line $log | sed 's/^/  | /'  >&2 
    else
        cat $log | sed 's/^/  | /'  >&2 
    fi
    echo
  fi
done

exit $program_exit
